# Generated by Django 4.2.5 on 2023-11-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='dateOfBirth',
            field=models.DateField(),
        ),
    ]
