# Generated by Django 4.2.5 on 2023-11-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sponsor_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='description',
        ),
    ]
