# Generated by Django 4.2.5 on 2023-11-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sponsor_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='gender',
            new_name='genderr',
        ),
    ]
