# Generated by Django 4.2.5 on 2023-11-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_gender_sponsor_genderr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='genderr',
            new_name='gender',
        ),
    ]
