# Generated by Django 4.2.5 on 2023-11-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_dateofbirth_sponsor_dateofbirth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.DeleteModel(
            name='Sponsorship',
        ),
    ]
