# Generated by Django 4.2.5 on 2023-11-11 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_sponsor_delete_sponsorship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('netWorth', models.FloatField(default=0.0)),
                ('gender', models.CharField(max_length=15)),
                ('dateOfbirth', models.DateField()),
                ('fortune_origin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hero')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.villain')),
            ],
        ),
    ]
